### PR TITLE
Adding some suggestions

### PR DESCRIPTION
**Pull request by mtlynch**
I made some inline changes for the issues I noticed. I'm not expecting you to just merge these changes (though you're welcome to). I just thought it would be the easiest way of providing feedback. I'll also add some additional notes through Reviewable.

---
This change is [Reviewable](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1)

### CODE REVIEW

**Review by mtlynch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1)* status: 0 of 1 files reviewed, 18 unresolved discussions

*[a discussion](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTVyGRB_iVrT3yUMje:-LnTVyGRB_iVrT3yUMjf:blaajgh) (no related file):*
### General notes

## Passive voice

The guide makes frequent use of the passive voice (e.g. "so they can be used by any test" vs. "so that any test can use them"). Passive voice makes technical content more difficult to read. Especially difficult is passive voice that omits the subject of the sentence (e.g., "the command is sent to foo") because the reader doesn't know who's taking action in the sentence.

## Your vs. Our

The tutorial switches between "your" and "our." Maybe it's intentional (e.g., *your* file but *our* project), but just wanted to flag it in case it's not.

## Trailing whitespace

Several lines have trailing whitespace. This should be pretty easy to find/replace.

---
___
*[README.md, line 38 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTVRTM-1WUldksWEFR:-LnTVRTM-1WUldksWEFS:blz5lkq) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L38)):*
> ```Markdown
> 
> These WebDriver executables will act as a proxy between our test automation code and browser instances.
> Make sure their versions match the versions of the browsers, or else problems may happen.
> ```

This is a bit vague. Consider clarifying.
___
*[README.md, line 40 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTVVcXANrvX7rDc5e3:-LnTVVcXANrvX7rDc5e4:b-xh5q4f) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L40)):*
> ```Markdown
> Make sure their versions match the versions of the browsers, or else problems may happen.
> The WebDriver executables must also be on your [system path](https://en.wikipedia.org/wiki/PATH_(variable)).
> To verify, simply try to run them from the terminal, and then close them.
> ```

It would be helpful to list the exact command the users should run.
___
*[README.md, line 69 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTV_KV4QQ9vSgWTxpm:-LnTV_KV4QQ9vSgWTxpn:bwqq7ot) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L69)):*
> ```Markdown
> 
> * [`example/1-first-test`](https://github.com/AndyLPK247/djangocon-2019-web-ui-testing/tree/example/1-first-test)
> * `example/2-webdriver-setup`
> ```

Do these need the `prefix/` example? If everything has the same prefix, the prefix seems unnecessary.

Also, I noticed that the branches didn't have all the README changes from master, so might be useful to rebase them.
___
*[README.md, line 89 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTVoZ58fEUikiWk_9K:-LnTVoZ58fEUikiWk_9L:b-qitl6h) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L89)):*
> ```Markdown
> Writing a test case first helps us form our thoughts well.
> 
> Consider the following test case:
> ```

It might be helpful to frame this a bit more. If the user has never seen a Gherkin test before, this might be confusing.
___
*[README.md, line 101 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTVsLF38uTZViFAGmw:-LnTVsLF38uTZViFAGmx:bkj2f0n) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L101)):*
> ```Markdown
> 
> Let's implement this test using pytest.
> Create a new file named `test_search.py` under the `tests` directory,
> ```

This confused me a bit. Was the user supposed to save the Gherkin test anywhere or is that a mental exercise?
___
*[README.md, line 156 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTW_Dg4VpEfoZ_uFwc:-LnTW_Dg4VpEfoZ_uFwd:b-ectp09) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L156)):*
> ```Markdown
> 
> Every test should use its own WebDriver instance.
> This keeps things simple and safe.
> ```

Might be useful to elaborate a bit on the specifics of why this is important.
___
*[README.md, line 159 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTWbspE_DL9PNffZF3:-LnTWbspE_DL9PNffZF4:b-nu8p2z) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L159)):*
> ```Markdown
> The best way to set up the WebDriver instance is to use a
> [pytest fixture](https://docs.pytest.org/en/latest/fixture.html).
> Fixtures are basically setup and cleanup functions.
> ```

This could use a bit more explanation. If the reader is new to testing, they likely don't know what setup and cleanup functions are.
___
*[README.md, line 245 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTWlYd8vSyUcPwaBo3:-LnTWlYd8vSyUcPwaBo4:b-bvv3t0) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L245)):*
> ```Markdown
>    * Get the title
> 
> Understanding interactions with the Web app is more important than the code.
> ```

I didn't understand what this sentence meant.
___
*[README.md, line 264 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTWtfY8bc6yKuk0J0B:-LnTWtfY8bc6yKuk0J0C:b-qz5bbe) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L264)):*
>`DuckDuckGoSearchPage` and `DuckDuckGoResultPage`

Personal style quibble, but I'd just call these `Search` and `Results`. They're in the "pages" package, so adding "Page" to every class name is redundant. And presumably every page is testing the same application (DuckDuckGo), so the prefix becomes meaningless if every class has it.
___
*[README.md, line 324 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTX7rF9TmII0Ir1yX3:-LnTX7rF9TmII0Ir1yX4:b-c1ay7x) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L324)):*
> ```Markdown
>   search_page = DuckDuckGoSearchPage(browser)
>   result_page = DuckDuckGoResultPage(browser)
>   PHRASE = "panda"
> ```

Obligatory suggestion to [eliminate the constant](https://mtlynch.io/good-developers-bad-tests/#dare-to-violate-dry).
___
*[README.md, line 361 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTXJM_CltwZowF2Fc-:-LnTXJM_CltwZowF2Fc0:b-mqwxlj) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L361)):*
> ```Markdown
> Every "thing" on a Web page is a Web *element*:
> buttons, labels, dropdowns, input fields, etc.
> Elements on the page are specified using HTML.
> ```

This is an example of particularly nasty passive voice because it omits the subject. "Specified" by whom? This creates ambiguity because the reader could take this to mean that the web author specifies elements on the page using HTML. Or the reader could take it to mean that the test developer specifies elements they want to interact with using HTML (which is probably not what you mean).
___
*[README.md, line 685 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTXZ0b82NDyg86MztZ:-LnTXZ0cDdBeeQP52TJG:bf6w0nm) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L685)):*
> ```Markdown
>   # Locators
> 
>   SEARCH_INPUT = (By.ID, 'search_form_input')
> ```

Suggest making this `_SEARCH_INPUT` since it isn't really part of the class' public interface. Ditto for `self.browser` -> `self._browser`.
___
*[README.md, line 699 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTXOefANfSHFX0Vdr2:-LnTXOeg8M-cimEJCuLI:bkg2my0) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L699)):*
> ```Markdown
>   # Interaction Methods
> 
>   def result_count_for_phrase(self, phrase):
> ```

This confused me a bit because the results page shouldn't really need to know the query terms to count how many results are on the page. Everything needed is right on the page. Also, I suspect using the phrase in the XPath actually leads to incorrect results sometimes when the query has stopwords that the search engine ignores (e.g., "the taylor swift") or uses different casing than appears in the results (e.g., "TAYlor swIFT").
___
*[README.md, line 700 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTXajW6UmsSZfTL0Kg:-LnTXajW6UmsSZfTL0Kh:b-7h2kyd) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L700)):*
> ```Markdown
> 
>   def result_count_for_phrase(self, phrase):
>     results = self.browser.find_elements(*self.PHRASE_RESULTS(phrase))
> ```

This is maybe just a style preference, but to me, the following is much more clear:

```python
results = self.browser.find_elements(By.ID, 'search_form_input')
```

The `By` constants are there specifically to make the function calls literate ("fine elements by ID"). Splitting it up in constants prevents that.

Ditto for `PHRASE_RESULTS` and the constants for the other page class.
___
*[README.md, line 818 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTYCjyEsiHUNvkW-DU:-LnTYCjyEsiHUNvkW-DV:b-2fvu75) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L818)):*
> ```Markdown
>   elif config['browser'] == 'Chrome':
>     b = selenium.webdriver.Chrome()
>   else:
> ```

Suggest checking all options explicitly. Otherwise "Safari" implicitly becomes Chrome Headless, when it should really be an error.
___
*[README.md, line 823 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTYKefC3d9QTciglz0:-LnTYKefC3d9QTciglz1:bff6sg) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L823)):*
> ```Markdown
>     b = selenium.webdriver.Chrome(options=opts)
> 
>   # Make its calls wait up to 10 seconds for elements to appear
> ```

Comment no longer applies.
___
*[README.md, line 1029 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTYO3KB1Rlrlnpx6rA:-LnTYO3KB1Rlrlnpx6rB:bqsemx1) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L1029)):*
> ```Markdown
> 
> * 1 test per processor minimizes total execution time without slowing down individual tests
> * 2 tests per processor minimizes total execution time further but warps individual tests
> ```

"Warps" is a bit vague. Like causes flakiness or slows them down?

**Review by mtlynch — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1)* status: 0 of 1 files reviewed, 18 unresolved discussions

___
*[README.md, line 699 at r1](https://reviewable.io/reviews/andylpk247/djangocon-2019-web-ui-testing/1#-LnTXOefANfSHFX0Vdr2:-LnTYr9B-dBn5b3gNLzc:b-bk3wkx) ([raw file](https://github.com/andylpk247/djangocon-2019-web-ui-testing/blob/85cace001af43610ca42fa61b0d3d651361e9377/README.md#L699)):*
<details><summary><i>Previously, mtlynch (Michael Lynch) wrote…</i></summary><blockquote>

This confused me a bit because the results page shouldn't really need to know the query terms to count how many results are on the page. Everything needed is right on the page. Also, I suspect using the phrase in the XPath actually leads to incorrect results sometimes when the query has stopwords that the search engine ignores (e.g., "the taylor swift") or uses different casing than appears in the results (e.g., "TAYlor swIFT").
</blockquote></details>

It feels like there's a mismatch between the intent of the test and the functionality of the Page class. Consider changing the function to be like `text_appears_in_results`.

**Comment by AndyLPK247** [comment]
Thanks so much for providing this excellent feedback! Here are some quick comments from me:

1. I probably should have mentioned that this will be a guided tutorial. I will give small lectures before each part, and then students will complete each part on their own. Nevertheless, it's very helpful to see areas in each part that needed extra context to make sense without the slides.
2. I'll definitely improve the setup instructions.
3. The branch prefixes separate the "example" code from the student's "tutorial" code.
4. I purposefully use tuples for locators instead of writing them in-line with "find_element" calls in order to separate locators as a concern and also to make them reusable. It may seem trivial with a test project this small, but it's vital for scalability when a test project has hundreds to thousands of end-to-end Web tests.
5. Good catch on the browser config selection. I'll definitely update that.
6. Good catch on the result link count. I'm torn about what to do. On one hand, the test is explicitly simple and accepts finding at least one result that matches the search phrase text. I've also seen horrible practices where people will loop over lists of elements when they can instead use single parametrized locators. However, the correctness and consistency of the assertion is questionable, and the logic behind the assertion may be too much of a mental gymnastic for this tutorial. Regardless, your feedback on this point is very helpful!
7. I used the suffix "Page" for the page object classes because (a) that's conventional of the pattern and (b) it distinguishes the class for covering a page instead of, say, a component. Again, for the size of this project, it's trivial, but I want to side with being explicit over implicit.

I'm making many updates now. Your feedback is very helpful!

**Comment by AndyLPK247** [comment]
I'm closing this pull request because I incorporated the feedback into the latest version of the README. I still need to update the code, which means I'll probably delete and recreate the branches to keep their histories clean. @mtlynch, again, many thanks for taking your time to review this tutorial. Your feedback helped to make it much better!

**Comment by mtlynch** [comment]
Cool, glad it was helpful!

**Pull request closed without merging**
